export const GET_LOGIN_REQUEST = "GET_LOGIN_REQUEST";
export const GET_LOGIN_SUCCESS = "GET_LOGIN_SUCCESS";
export const GET_LOGIN_ERROR = "GET_LOGIN_ERROR";

export const GET_ADMIN_SUCCESS = "GET_ADMIN_SUCCESS";


export const LOGOUT_ACTION = "LOGOUT_ACTION";
